spring:
  config:
    import: classpath:secrets.yaml
  application:
    name: "test_users"
  datasource:
    url: ${dockerPostgres.url}
    username: ${dockerPostgres.username}
    password: ${dockerPostgres.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
user:
  required_age: 18